name: render-it

on: push
permissions:
  contents: read
  pages: write
  id-token: write
defaults:
  run:
    shell: bash

jobs:
    render:
        runs-on: ubuntu-latest
        steps:
        - name: setup
          uses: prefix-dev/setup-pixi@v0.8.3
          with:
            pixi-version: v0.48.2
            cache: true
        - name: render
          run: pixi run render --output-dir paper
        - name: deploy
          id: deployment
          uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
          with:
            path: paper
