name: render-it

on: push
permissions:
  contents: read
  pages: write
  id-token: write
defaults:
  run:
    shell: bash

jobs:
    render:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: setup
          uses: prefix-dev/setup-pixi@v0.8.3
          with:
            pixi-version: v0.48.2
            cache: true
        - name: render
          run: pixi run render --output-dir paper
        - name: upload
          id: upload
          uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
          with:
            path: paper
    deploy:
        if: "github.repository_owner == 'digital-earths-global-hackathon' && (github.event_name == 'schedule' || (github.event_name == 'push'))"
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: render
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
